Always write all data to serial
When using `write` one needs to handle the case where not all data is
written. This fixes a clippy reported problem:

    error: written amount is not handled. Use `Write::write_all` instead
      --> src/lib.rs:63:9
       |
    63 |         self.0.write(&[0])?;
       |         ^^^^^^^^^^^^^^^^^^^
       |
       = note: `#[deny(clippy::unused_io_amount)]` on by default
       = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount